name: Testing

on: [push]

jobs:
    contract-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get npm cache directory
              id: npm-cache
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.npm-cache.outputs.dir }}
                      **/node_modules
                  key: ${{ github.job }}-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ github.job }}-${{ runner.os }}-node-

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install contract package dependencies
              run: npm ci

            - name: Build contract package
              run: npm run build

            - name: Run contract tests
              run: npm test

            - name: Run contract coverage
              run: npm run coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get npm cache directory
              id: npm-cache
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.npm-cache.outputs.dir }}
                      **/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint
